---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    path: airflow
    repoURL: https://github.com/bitnami/charts/tree/master/bitnami
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
