
{{- range $app := .Values.Applications }}
{{- if $app.enabled }}

{{- if $app.namespace}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{$app.namespace}}
{{- end -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{$app.namespace}}
  project: default
  source:
    path: {{$app.chart_path}}
{{- if $app.chart_name}}
    chart: {{$app.chart_name}}
{{- end -}}
{{- if $app.repo_url}}
    repoURL: {{$app.repo_url}}
{{- end -}}
{{- if $app.repo_branch}}
    targetRevision: {{$app.repo_branch}}
{{- end -}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end -}}
{{- end -}}
