---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    path: gitlab
    repoURL: https://github.com/BoulderES/gitlab_chart.git
    targetRevision: HEAD
    valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
