---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/BoulderES/ingress-nginx.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-lab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
