---
apiVersion: v1
kind: Namespace
metadata:
  name: jitsi
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jitsi
  namespace: argocd
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/BoulderES/jitsi.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: jitsi
