---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BoulderES/monitoring.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
