---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-tools-poc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skywalking-poc
  namespace: argocd
spec:
  project: default
  source:
    path: skywalking-poc
    repoURL: https://bitbucket.org/iccgit/cps-monitoring-poc.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-lab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-tools-poc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-eck
  namespace: argocd
spec:
  project: default
  source:
    path: elk-eck
    repoURL: https://github.com/BoulderES/monitoring-tools-poc.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-lab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-tools-poc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-poc
  namespace: argocd
spec:
  project: default
  source:
    path: elk-poc
    repoURL: https://github.com/BoulderES/monitoring-tools-poc.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-lab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-tools-poc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-stack-poc
  namespace: argocd
spec:
  project: default
  source:
    path: grafana-stack-poc
    repoURL: https://bitbucket.org/iccgit/cps-monitoring-poc.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-lab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-tools-poc
