---
apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/BoulderES/pgadmin.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - values-lab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin
