---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/BoulderES/postgres.git
    targetRevision: HEAD
#    repoURL: https://github.com/bitnami/charts.git
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
