---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  repository.credentials: |
    - url: {{ $.Values.git.url }}
      passwordSecret:
        key: password
        name: repo-manifests-git-secret
      usernameSecret:
        key: username
        name: repo-manifests-git-secret
